### PR TITLE
Fix telegram test flake

### LINKED ISSUE #867: Telegram test is flaky
https://github.com/fluxcd/notification-controller/blob/39f345231ffbb699d41aa129fe9f28d56a207c0c/internal/notifier/telegram_test.go#L46 fails sometimes because the metadata string is assembled from a map where the iteration order is non-deterministic.

### PR DESCRIPTION
**Pull request by makkes**
The test would sometimes fail because the metadata lines are built from a map and map iteration order in Go is non-deterministic.  Therefore, the lines may be ordered differently between different test runs.

Now, the test sorts the metadata lines of the telegram message so they are always the same and only then verifies the expected output.

closes #867

### CODE REVIEW

File: internal/notifier/telegram_test.go [hunk 1]
```diff
@@ -52,3 +65,10 @@ func TestTelegram_Post(t *testing.T) {
 	err = telegram.Post(context.TODO(), ev)
 	require.NoError(t, err)
 }
+
+/*
```
Comment (matheuscscp) [inline internal/notifier/telegram_test.go:69]: Is this comment left here on purpose?

Comment (makkes) [reply internal/notifier/telegram_test.go]: Oops, no. I removed it now.

**Review by matheuscscp — APPROVED** [review]
LGTM!

**Review by stefanprodan — APPROVED** [review]
